spring.application.name=storage-service
server.port=8082

# MinIO
quantum-provenance.minio.endpoint=http://localhost:9000
quantum-provenance.minio.access-key=minioadmin
quantum-provenance.minio.secret-key=minioadminpassword
quantum-provenance.minio.bucket-name=quantum-provenance-manifests
