spring.application.name=blockchain-service
server.port=8083

# Web3j / EVM
quantum-provenance.blockchain.rpc-url=http://localhost:8545
quantum-provenance.blockchain.private-key=0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80
