spring.application.name=api-gateway
server.port=8080

# Internal service routing
quantum-provenance.shipment-service.url=http://localhost:8084
quantum-provenance.crypto-service.url=http://localhost:8081
quantum-provenance.storage-service.url=http://localhost:8082
quantum-provenance.blockchain-service.url=http://localhost:8083

# ABAC policy templates location
quantum-provenance.abac.policy-dir=../../infra/config/abac-policy-templates
